language: java
jdk:
  - openjdk11

branches: # 어느 브랜치가 푸시될 때 수행할지 지정
  only: # master 브랜치에 push될 때만 수행
    - master

# Travis CI 서버의 Home
cache: # gradle을 통해 의존성을 받게 되면 해당 위치에 캐싱. 다음 배포 다시 받지 않도록
  directories:
    - '$HOME/.m2/repository'
    - '$HOME/.gradle'

before_install:
  - chmod +x gradlew

script: "./gradlew clean build" # master 브랜치에 푸시되었을 때 수행하는 명령어

before_deploy: # deploy 명령어 실행전에 수행. CodeDeploy는 JAR파일을 인식하지 못해 JAR+기타설정파일을 압축
  - zip -r aws-webservice * # 현재 위치의 모든 파일을 압축. 명령어의 마지막 위치는 본인의 프로젝트 명
  - mkdir -p deploy # deploy 디렉토리를 Travis CI가 실행 중인 생성
  - mv aws-webservice.zip deploy/aws-webservice.zip # 파일을 이동

deploy: # S3로 파일 업로드 혹은 CodeDeploy로 배포 등 외부 서비스와 연동될 행위를 선언
  - provider: s3
    access_key_id: $AWS_ACCESS_KEY
    secret_access_key: $AWS_SECRET_KEY
    bucket: spring-webservice-build # S3 버킷
    region: ap-northeast-2
    skip_cleanup: true
    acl: private # 파일 접근 private로
    local_dir: deploy # before_deploy에서 생성한 디렉토리. 해당 위치의 파일들만 S3로 전송
    wait-until-deployed: true

# CI 실행 완료 시 알람 (+ 슬랙알림도!)
notifications:
  email:
    recipients:
      - girawhale@naver.com